name: CI
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK and Maven
        uses: actions/setup-java@v2
        with:
          java-version: '>=11.0.0'
          distribution: 'adopt'
          cache: 'maven'

      - name: Build
        run: mvn compile
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Test
        run: mvn test
        env:
          GITHUB_TOKEN: ${{ github.token }}
